"""Day 4 orchestration script for the Credit Card Fraud Detection &
Risk Scoring System.

This script trains baseline models (Dummy, Logistic Regression, Random
Forest) on the Day 3 processed training data and evaluates them on the
validation set only. The test set is intentionally left untouched on
Day 4; it is reserved for final evaluation later in the project.

Run from the repository root:

    python3 scripts/run_day4_baseline_models.py
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, Tuple

import pandas as pd

# Ensure the project root is importable when this script is executed
# directly, e.g. `python3 scripts/run_day4_baseline_models.py` from the
# repository root.
PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.models.baseline_models import (  # noqa: E402
    get_model_summary,
    save_models,
    train_baseline_models,
)
from src.evaluation.classification_metrics import (  # noqa: E402
    evaluate_models,
    find_best_model_by_pr_auc,
    metrics_to_dataframe,
    save_metrics_csv,
    save_metrics_json,
)
from src.evaluation.model_report import save_day4_baseline_model_report  # noqa: E402


# ---------------------------------------------------------------------------
# Default paths
# ---------------------------------------------------------------------------

DEFAULT_PROCESSED_DIR = Path("data/processed")
DEFAULT_MODELS_DIR = Path("artifacts/models")
DEFAULT_METRICS_DIR = Path("reports/metrics")
DEFAULT_REPORT_PATH = Path("reports/day4_baseline_model_summary.md")

REQUIRED_PROCESSED_FILES = (
    "X_train_processed.parquet",
    "X_val_processed.parquet",
    "y_train.parquet",
    "y_val.parquet",
)

TARGET_COLUMN = "Class"


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------


def load_processed_training_data(
    processed_dir: str | Path = DEFAULT_PROCESSED_DIR,
) -> Tuple[pd.DataFrame, pd.Series, pd.DataFrame, pd.Series]:
    """Load Day 3 processed train and validation data.

    Only training and validation data is loaded. The processed test set
    is intentionally not touched here, since Day 4 must not perform any
    final test-set evaluation.

    Args:
        processed_dir: Directory containing the processed parquet files
            generated by ``scripts/run_day3_preprocessing.py``.

    Returns:
        A tuple of ``(X_train, y_train, X_val, y_val)``.

    Raises:
        FileNotFoundError: If any required processed file is missing.
        ValueError: If the loaded data fails basic consistency checks
            (mismatched row counts, leaked target column, or a missing
            class in either split).
    """
    processed_dir = Path(processed_dir)

    file_paths = {name: processed_dir / name for name in REQUIRED_PROCESSED_FILES}
    missing = [str(path) for path in file_paths.values() if not path.exists()]
    if missing:
        missing_list = "\n".join(f"  - {path}" for path in missing)
        raise FileNotFoundError(
            "Missing required Day 3 processed file(s):\n"
            f"{missing_list}\n"
            "Please run `python3 scripts/run_day3_preprocessing.py` first."
        )

    X_train = pd.read_parquet(file_paths["X_train_processed.parquet"])
    X_val = pd.read_parquet(file_paths["X_val_processed.parquet"])
    y_train_df = pd.read_parquet(file_paths["y_train.parquet"])
    y_val_df = pd.read_parquet(file_paths["y_val.parquet"])

    if TARGET_COLUMN not in y_train_df.columns:
        raise ValueError(
            f"Expected column '{TARGET_COLUMN}' not found in y_train.parquet."
        )
    if TARGET_COLUMN not in y_val_df.columns:
        raise ValueError(
            f"Expected column '{TARGET_COLUMN}' not found in y_val.parquet."
        )

    y_train = y_train_df[TARGET_COLUMN].rename(TARGET_COLUMN)
    y_val = y_val_df[TARGET_COLUMN].rename(TARGET_COLUMN)

    if len(X_train) != len(y_train):
        raise ValueError(
            "Row count mismatch between X_train "
            f"({len(X_train)}) and y_train ({len(y_train)})."
        )
    if len(X_val) != len(y_val):
        raise ValueError(
            "Row count mismatch between X_val "
            f"({len(X_val)}) and y_val ({len(y_val)})."
        )

    if TARGET_COLUMN in X_train.columns:
        raise ValueError(
            f"Target column '{TARGET_COLUMN}' must not be present in X_train."
        )
    if TARGET_COLUMN in X_val.columns:
        raise ValueError(
            f"Target column '{TARGET_COLUMN}' must not be present in X_val."
        )

    if y_train.nunique() < 2:
        raise ValueError(
            "y_train must contain both classes (0 and 1) to train baseline models."
        )
    if y_val.nunique() < 2:
        raise ValueError(
            "y_val must contain both classes (0 and 1) to evaluate baseline models."
        )

    return X_train, y_train, X_val, y_val


# ---------------------------------------------------------------------------
# CLI argument parsing
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for the Day 4 baseline modeling script."""
    parser = argparse.ArgumentParser(
        description=(
            "Train baseline fraud detection models (Dummy, Logistic "
            "Regression, Random Forest) on Day 3 processed training data "
            "and evaluate them on the validation set only."
        )
    )
    parser.add_argument(
        "--processed-dir",
        type=str,
        default=str(DEFAULT_PROCESSED_DIR),
        help="Directory containing Day 3 processed parquet files.",
    )
    parser.add_argument(
        "--models-dir",
        type=str,
        default=str(DEFAULT_MODELS_DIR),
        help="Directory to save trained baseline model artifacts.",
    )
    parser.add_argument(
        "--metrics-dir",
        type=str,
        default=str(DEFAULT_METRICS_DIR),
        help="Directory to save validation metrics JSON/CSV files.",
    )
    parser.add_argument(
        "--report-path",
        type=str,
        default=str(DEFAULT_REPORT_PATH),
        help="Path to save the Day 4 baseline model Markdown report.",
    )
    return parser.parse_args()


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------


def run_day4_baseline_models(
    processed_dir: str | Path = DEFAULT_PROCESSED_DIR,
    models_dir: str | Path = DEFAULT_MODELS_DIR,
    metrics_dir: str | Path = DEFAULT_METRICS_DIR,
    report_path: str | Path = DEFAULT_REPORT_PATH,
) -> Dict[str, Any]:
    """Run the full Day 4 baseline modeling workflow.

    Loads Day 3 processed training/validation data, trains baseline
    models, evaluates them on the validation set, and saves model
    artifacts, metrics files, and a Markdown report. The test set is
    never loaded or used in this function.

    Args:
        processed_dir: Directory with Day 3 processed parquet files.
        models_dir: Directory to save trained model artifacts.
        metrics_dir: Directory to save metrics JSON/CSV files.
        report_path: Path to save the Markdown report.

    Returns:
        A dictionary summarizing the results of the run, including
        dataset shapes, model summary, validation metrics, the best
        model by PR-AUC, and the paths of all generated artifacts.
    """
    processed_dir = Path(processed_dir)
    models_dir = Path(models_dir)
    metrics_dir = Path(metrics_dir)
    report_path = Path(report_path)

    print("Step 1/7: Loading Day 3 processed train and validation data...")
    X_train, y_train, X_val, y_val = load_processed_training_data(processed_dir)
    dataset_shapes = {
        "X_train_shape": tuple(X_train.shape),
        "y_train_shape": tuple(y_train.shape),
        "X_val_shape": tuple(X_val.shape),
        "y_val_shape": tuple(y_val.shape),
    }
    print(f"  X_train shape: {dataset_shapes['X_train_shape']}")
    print(f"  X_val shape:   {dataset_shapes['X_val_shape']}")

    print("Step 2/7: Training baseline models on training data only...")
    models = train_baseline_models(X_train, y_train)
    model_summary = get_model_summary(models)
    print(f"  Trained models: {list(models.keys())}")

    print("Step 3/7: Evaluating models on the validation set only...")
    all_metrics = evaluate_models(models, X_val, y_val)
    metrics_df = metrics_to_dataframe(all_metrics)

    print("Step 4/7: Identifying the best baseline model by PR-AUC...")
    best_model_name = find_best_model_by_pr_auc(all_metrics)
    print(f"  Best model by PR-AUC: {best_model_name}")

    print("Step 5/7: Saving trained model artifacts...")
    model_paths = save_models(models, output_dir=models_dir)

    print("Step 6/7: Saving validation metrics (JSON and CSV)...")
    metrics_json_path = metrics_dir / "day4_baseline_metrics.json"
    metrics_csv_path = metrics_dir / "day4_baseline_metrics.csv"
    metrics_paths = {
        "metrics_json": save_metrics_json(all_metrics, output_path=metrics_json_path),
        "metrics_csv": save_metrics_csv(all_metrics, output_path=metrics_csv_path),
    }

    print("Step 7/7: Generating the Day 4 baseline model report...")
    saved_report_path = save_day4_baseline_model_report(
        model_summary=model_summary,
        metrics_df=metrics_df,
        best_model_name=best_model_name,
        model_paths=model_paths,
        metrics_paths=metrics_paths,
        report_path=report_path,
    )

    return {
        "dataset_shapes": dataset_shapes,
        "model_summary": model_summary,
        "metrics": all_metrics,
        "metrics_df": metrics_df,
        "best_model_name": best_model_name,
        "model_paths": model_paths,
        "metrics_paths": metrics_paths,
        "report_path": saved_report_path,
    }


def print_success_message(results: Dict[str, Any]) -> None:
    """Print a clean, human-readable summary after a successful Day 4 run."""
    model_paths = results.get("model_paths", {})
    metrics_paths = results.get("metrics_paths", {})

    print("\n" + "=" * 70)
    print("Day 4 baseline modeling completed successfully.")
    print("=" * 70)
    print(f"Models trained: {len(model_paths)}")
    for name, path in model_paths.items():
        print(f"  - {name}: {path}")
    print(f"Best model by PR-AUC: {results.get('best_model_name')}")
    print("Metrics files:")
    for name, path in metrics_paths.items():
        print(f"  - {name}: {path}")
    print(f"Report saved to: {results.get('report_path')}")
    print(
        "Reminder: the test set was NOT used on Day 4. "
        "It remains untouched for final evaluation later in the project."
    )
    print("=" * 70)


def main() -> None:
    """Entry point for the Day 4 baseline modeling script."""
    args = parse_args()

    try:
        results = run_day4_baseline_models(
            processed_dir=args.processed_dir,
            models_dir=args.models_dir,
            metrics_dir=args.metrics_dir,
            report_path=args.report_path,
        )
        print_success_message(results)
    except FileNotFoundError as exc:
        print(f"\nError: required input file not found.\n{exc}", file=sys.stderr)
        sys.exit(1)
    except ValueError as exc:
        print(f"\nError: invalid data encountered.\n{exc}", file=sys.stderr)
        sys.exit(1)
    except Exception as exc:  # noqa: BLE001
        print(f"\nUnexpected error during the Day 4 pipeline: {exc}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
